baseURL = "https://andersoncastillol.github.io/capstone-project"
publishDir = "docs"
languageCode = "en"
title = "Bike Availability Prediction Project"
theme = "gokarna"
disqusShortname = "ilusionismo-con-github-pages"
author = 'Pau Torrente - Anderson Castillo - Rohit Lachman'

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  showPostsOnHomePage = "popular"
  footer = "The Cyclists"
  description = "Data Science & Machine Learning Final Project"

metaKeywords = ["blog", "gokarna", "hugo"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Documentation"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/AndersonCastilloL/capstone-project"
    weight = 4
